INSERT INTO Long_term (Record_id, Long_term_effect, Able_to_continue_career) VALUES
('R006', 'Chronic knee pain, may affect future performance', FALSE),
('R033', 'Reduced mobility in shoulder joint', FALSE),
('R057', 'Persistent ankle instability', TRUE),
('R014', 'Long-term back stiffness', FALSE),
('R068', 'Recurring wrist discomfort', TRUE),
('R040', 'Partial ligament tear, may limit agility', FALSE),
('R026', 'Ongoing muscle weakness in leg', FALSE),
('R089', 'Reduced flexibility, needs careful training', TRUE),
('R078', 'Mild long-term joint pain', TRUE),
('R011', 'Chronic hamstring tightness', FALSE),
('R005', 'Reduced endurance due to injury', TRUE),
('R063', 'Long-term shoulder discomfort', FALSE),
('R080', 'Persistent hip stiffness', TRUE),
('R009', 'Ligament weakness in knee', TRUE),
('R003', 'Chronic tendon inflammation', TRUE),
('R038', 'Partial cartilage damage, may flare up', TRUE),
('R059', 'Reduced mobility in ankle', FALSE),
('R085', 'Mild long-term back pain', FALSE),
('R022', 'Recurring neck discomfort', FALSE),
('R032', 'Long-term wrist limitation', FALSE),
('R016', 'Persistent muscle soreness', TRUE),
('R073', 'Reduced agility in leg', TRUE),
('R053', 'Chronic shoulder pain', FALSE),
('R047', 'Ongoing knee discomfort', FALSE),
('R034', 'Mild tendon damage', TRUE),
('R060', 'Partial ligament tear, rehab needed', TRUE),
('R002', 'Ongoing ankle discomfort', FALSE),
('R074', 'Chronic wrist pain', TRUE),
('R045', 'Reduced flexibility in leg', TRUE),
('R001', 'Persistent shoulder discomfort', TRUE),
('R070', 'Long-term back limitation', FALSE),
('R050', 'Recurring hamstring tightness', TRUE),
('R081', 'Mild long-term joint pain', TRUE),
('R024', 'Partial muscle damage', FALSE);